artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_Model.h5
  UPDATED_BASE_MODEL: Update_VGG16_Model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

source_data_paths:
  - ../dataset/training_set/dogs
  - ../dataset/training_set/cats
data_paths:
  - data/cats
  - data/dogs